export declare const Command: {
    readonly M: 2;
    readonly L: 2;
    readonly H: 1;
    readonly V: 1;
    readonly C: 6;
    readonly S: 4;
    readonly Q: 4;
    readonly T: 2;
    readonly A: 7;
    readonly Z: 0;
};
export declare const CommandSet: Set<string>;
export type Command = keyof typeof Command;
export type PathCommand<Type extends string, Args extends unknown[]> = [Type, ...Args];
export type MoveCommand = PathCommand<'M', [number, number]>;
export type LineCommand = PathCommand<'L', [number, number]>;
export type HorizonalCommand = PathCommand<'H', [number]>;
export type VerticalCommand = PathCommand<'V', [number]>;
export type ArcCommand = PathCommand<'A', [number, number, number, 0 | 1, 0 | 1, number, number]>;
export type QuadCommand = PathCommand<'Q', [number, number, number, number]>;
export type QuadSmoothCommand = PathCommand<'T', [number, number]>;
export type CubicCommand = PathCommand<'C', [number, number, number, number, number, number]>;
export type CubicSmoothCommand = PathCommand<'S', [number, number, number, number]>;
export type CloseCommand = PathCommand<'Z', []>;
export type SVGPathCommand = MoveCommand | LineCommand | HorizonalCommand | VerticalCommand | ArcCommand | QuadCommand | QuadSmoothCommand | CubicCommand | CubicSmoothCommand | CloseCommand;
export declare function pathFromSvgPathCommand<Path extends Path2D = Path2D>(path: Path, cmds: SVGPathCommand[]): void;
export declare function pathFromSvgPath(path: Path2D, data: string): boolean;
